name: Build and Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-xray

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            sdk_url: https://downloads.openwrt.org/releases/25.12.1/targets/x86/64/openwrt-sdk-25.12.1-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst

          - arch: mipsel
            sdk_url: https://downloads.openwrt.org/releases/25.12.1/targets/ramips/mt7621/openwrt-sdk-25.12.1-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd build-essential libncurses5-dev python3

      - name: Create temp dir
        run: echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Download SDK
        run: |
          wget -q -O "$SDK_HOME/sdk.tar.zst" "${{ matrix.sdk_url }}"

      - name: Unpack SDK
        run: |
          zstd -cd "$SDK_HOME/sdk.tar.zst" | tar -C "$SDK_HOME" --strip=1 -xf -

      - name: Link package
        run: |
          ln -s "${{ github.workspace }}" "$SDK_HOME/package/$PACKAGE_NAME"

      - name: Build package
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/$PACKAGE_NAME/compile V=s -j$(nproc)

      - name: Upload ipk
        uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ matrix.arch }}
          path: ${{ env.SDK_HOME }}/bin/packages/*.ipk

  release:
    name: Create Release & Upload All
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all ipks
        uses: actions/download-artifact@v4
        with:
          pattern: ipk-*
          merge-multiple: true
          path: ./output

      - name: List files
        run: ls -lh ./output

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./output/*.ipk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
